version: '3.9'


networks:
  net1:

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - "5430:5432"
    networks:
      net1:
        aliases:
          - database